# This is the configuration file for golangci-lint.
# Options for analysis running.
run:
  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path.
  # Default value is empty list,
  # but default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  skip-dirs:
    - cmd/apprepository-controller
    - pkg/external

linters-settings:
  goconst:
    # Minimal length of string constant.
    # Default: 3
    min-len: 2
    # Minimum occurrences of constant string count to trigger issue.
    # Default: 3
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/gardener/potter-hub
  gocritic:
    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # See https://github.com/go-critic/go-critic#usage -> section "Tags".
    # Default: []
    enabled-tags:
      - diagnostic
      - performance
      - experimental
      - opinionated
      - style
    disabled-checks:
      - whyNoLint
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - unnamedResult
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  # For a list of all supported linters, go here: https://github.com/golangci/golangci-lint#supported-linters
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

    # Don't enable
    #- depguard
    #- dogsled
    #- dupl
    #- funlen
    #- gocognit
    #- gocyclo
    #- godox
    #- gofmt
    #- lll
    #- maligned
    #- prealloc
    #- wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
