apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-potter-hub-internal-apprepository-controller
  labels:
    app: hub-k8s-potter-hub-internal-apprepository-controller
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-potter-hub-internal-apprepository-controller2
  labels:
    app: hub-k8s-potter-hub-internal-apprepository-controller
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
