apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-k8s-potter-hub-internal-apprepository-controller
  labels:
    app: hub-k8s-potter-hub-internal-apprepository-controller
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apprepository.replicaCount }}
  selector:
    matchLabels:
      app: hub-k8s-potter-hub-internal-apprepository-controller
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.linkerd.enabled }}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}
      labels:
        app: hub-k8s-potter-hub-internal-apprepository-controller
        release: {{ .Release.Name }}
        {{ .Values.apprepository.affinityLabel.key }}: {{ .Values.apprepository.affinityLabel.value }}
    spec:
      serviceAccountName: {{ .Values.apprepository.apprepositoryControllerServiceAccount }}
{{- include "kubeapps.imagePullSecrets" . | indent 6 }}
      containers:
      - name: controller
        image: {{ template "kubeapps.image" (list .Values.apprepository.image .Values.global) }}
        command:
        - /apprepository-controller
        args:
        - --logtostderr
        - --user-agent-comment=kubeapps/{{ .Chart.AppVersion }}
        - --repo-sync-image={{ template "kubeapps.image" (list .Values.apprepository.syncImage .Values.global) }}
        - --namespace={{ .Release.Namespace }}
        - --mongo-url={{ template "kubeapps.mongodb.fullname" . }}
        - --mongo-secret-name={{ .Values.mongodb.auth.existingSecret }}
        {{- if .Values.apprepository.crontab }}
        - --crontab={{ .Values.apprepository.crontab }}
        {{- end }}
        {{- if .Values.apprepository.enableDedicatedSyncNode }}
        - --enable-dedicated-sync-node
        {{- end }}
        resources:
{{ toYaml .Values.apprepository.resources | indent 12 }}
    {{- with .Values.apprepository.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.apprepository.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
    {{- with .Values.apprepository.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
