{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apprepo-syncjobs-cleanup
  labels:
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apprepo-syncjobs-cleanup
  labels:
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apprepo-syncjobs-cleanup
subjects:
- kind: ServiceAccount
  name: apprepo-syncjobs-cleanup
  namespace: {{ .Release.Namespace }}
{{- end -}}
