apiVersion: v1
kind: ServiceAccount
metadata:
  name: apprepo-syncjobs-cleanup2
  labels:
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}