apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kubeapps.fullname" . }}-health-auth
data:
  auth: {{ required "please set a username and password to secure the health endpoint" (htpasswd .Values.ingress.health.user .Values.ingress.health.password) | b64enc }}