apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.fullname" . }}
  labels:
    app: {{ template "kubeapps.name" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.frontend.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if and (.Values.frontend.service.loadBalancerIP) (eq .Values.frontend.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.frontend.service.port }}
  {{- if .Values.authProxy.enabled }}
    targetPort: proxy
  {{- else }}
    targetPort: http
  {{- end }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "kubeapps.fullname" . }}
    release: {{ .Release.Name }}
