apiVersion: batch/v1
kind: Job
metadata:
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
        release: {{ .Release.Name }}
    spec:
{{- include "kubeapps.imagePullSecrets" . | indent 6 }}
      containers:
      - name: kubectl
        image: {{ template "kubeapps.image" (list .Values.hooks.image .Values.global) }}
        command:
        - /bin/sh
        args:
        - -c
        - "kubectl delete secret -n {{ .Release.Namespace }} {{ .Values.mongodb.existingSecret }} || true"
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.apprepository.mongodbJobCleanupServiceAccount }}
    {{- with .Values.hooks.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
    {{- with .Values.hooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.hooks.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
