---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup2
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup2
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
