{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:
    app: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
subjects:
- kind: ServiceAccount
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: hub-k8s-apps-hub-internal-mongodb-jobs-cleanup2
  namespace: {{ .Release.Namespace }}
{{- end -}}
