{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hub-k8s-potter-hub-ui-backend
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - kubeapps.com
  resources:
  - apprepositories
  verbs:
  - get
  - list
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hub-k8s-potter-hub-ui-backend
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub-k8s-potter-hub-ui-backend
subjects:
- kind: ServiceAccount
  name: hub-k8s-potter-hub-ui-backend
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: hub-k8s-potter-hub-ui-backend2
  namespace: {{ .Release.Namespace }}

# the following role and rolebinding will be created in the controller namespace
# this is needed in order to read the "system-info" configmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system-info-cm-reader
  namespace: {{ .Values.controllerNamespace }}
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - system-info
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-info-cm-reader
  namespace: {{ .Values.controllerNamespace }}
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-info-cm-reader
subjects:
  - kind: ServiceAccount
    name: hub-k8s-potter-hub-ui-backend
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: hub-k8s-potter-hub-ui-backend2
    namespace: {{ .Release.Namespace }}
{{- end -}}
