apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-potter-hub-ui-backend
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-k8s-potter-hub-ui-backend2
  labels:
    app: hub-k8s-potter-hub-ui-backend
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
