apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.ui-backend.fullname" . }}
  labels:
    app: {{ template "kubeapps.ui-backend.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
