apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.ui-backend.fullname" . }}
  labels:
    app: {{ template "kubeapps.name" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.uiBackend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "kubeapps.ui-backend.fullname" . }}
    release: {{ .Release.Name }}
