apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
spec:
  conversion:
    strategy: None
  group: kubeapps.com
  names:
    kind: AppRepository
    listKind: AppRepositoryList
    plural: apprepositories
    shortNames:
      - apprepos
    singular: apprepository
  preserveUnknownFields: true
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
