apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
spec:
  conversion:
    strategy: None
  group: kubeapps.com
  names:
    kind: AppRepository
    listKind: AppRepositoryList
    plural: apprepositories
    shortNames:
      - apprepos
    singular: apprepository
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: AppRepositories
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
